### ISSUE TITLE
rescue_from Pundit::NotAuthorizedError

### ISSUE THREAD

**Issue by cjarrett** [highlands/serveapp#62]
app/controllers/application_controller:53 (
`authorize vars[:object].present? ? vars[:object] : vars[:objects]`) isn't catching Pundit::NotAuthorizedError correctly. Ideally, we catch these and interject `with: :user_not_authorized` so we can show the user a custom message without just throwing a 500.

**Comment by johndavid400** [comment]
are you still having issues with this? it is working for me
