### ISSUE TITLE
PG::UndefinedColumn: ERROR:  column users.name does not exist

### ISSUE THREAD

**Issue by cjarrett** [highlands/serveapp#86]
app/views/admin/projects/_form.html.haml:12

**Comment by freakinhuge** [comment]
What branch is this on? [_form.html.haml:12](https://github.com/highlands/serveapp/blob/master/app/views/admin/projects/_form.html.haml#L12) is a `.field` tag.

**Comment by cjarrett** [comment]
Line 11 in master and SDP-108.

**Comment by freakinhuge** [comment]
Fixed in SDP-108
